SELECT * FROM USER_ROLE;

-- INSERT INTO USER_ROLE(ID, NAME)
-- VALUES(1, 'admin');
--
-- INSERT INTO USER_ROLE(ID, NAME)
-- VALUES(2, 'doctor');
--
-- INSERT INTO USER_ROLE(ID, NAME)
-- VALUES(3, 'patient');